version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: api-user
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    container_name: api-user-nestjs
    build: . 
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: mysecretpassword
      DB_DATABASE: api-user 
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres-data: 
